all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/vision-sync-backend-dev.pem
    ansible_host_key_checking: false
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  children:
    bastion:
      hosts:
        bastion-host:
          ansible_host: "{{ bastion_public_ip }}"
          ansible_user: ubuntu
          
    mongodb:
      vars:
        ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q ubuntu@{{ bastion_public_ip }}"'
      hosts:
        mongodb-primary:
          ansible_host: "{{ mongodb_instance1_private_ip }}"
          mongodb_role: primary
          replica_set_priority: 2
        mongodb-secondary-1:
          ansible_host: "{{ mongodb_instance2_private_ip }}"
          mongodb_role: secondary
          replica_set_priority: 1
        mongodb-secondary-2:
          ansible_host: "{{ mongodb_instance3_private_ip }}"
          mongodb_role: secondary
          replica_set_priority: 1
          
    redis:
      vars:
        ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q ubuntu@{{ bastion_public_ip }}"'
      hosts:
        redis-server:
          ansible_host: "{{ redis_instance_private_ip }}"
          
    backend:
      vars:
        ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q ubuntu@{{ bastion_public_ip }}"'
      hosts:
        backend-server:
          ansible_host: "{{ backend_instance_private_ip }}"
          
    frontend:
      hosts:
        frontend-server:
          ansible_host: "{{ frontend_instance_public_ip }}"
          ansible_user: ubuntu